apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: {{ .Values.replicaCount }}  # Number of replicas
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Image from values.yaml
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # External port from values.yaml
      targetPort: {{ .Values.service.targetPort }}  # Port inside the container (usually 80)
      nodePort: {{ .Values.service.nodePort }}  # Expose on NodePort from values.yaml
  type: {{ .Values.service.type }}  # This will be NodePort as per values.yaml
