image:
  repository: myrepo/python-app  # Your image repository
  tag: v1.0.0  # Your image tag

replicaCount: 3  # Number of replicas for the deployment

service:
  type: LoadBalancer  # Type of service (could also be NodePort or ClusterIP)

resources: {}






